navikt/crm-hot-servicetjenesten

force-app/main/default/applications/Servicetjenesten.app-meta.xml
force-app/main/default/flexipages/NSV_UtilityBar.flexipage-meta.xml

Change name of the app

---

force-app/main/default/permissionsets/HOT_Servicetjenesten_Admin.permissionset-meta.xml
scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac
sfdx-project.json

TOLK-2646 : Gjøre crm-hot-servicetjenesten avhengig av crm-henvendelse

---

force-app/main/default/flows/HOT_STO_Case_Reserve.flow-meta.xml
force-app/scratch-org/standardValueSets/CaseStatus.standardValueSet-meta.xml

Reserve til meg flow og Case Status standard value set

Reserve til meg- flow

---

force-app/main/default/flexipages/HOT_Phone_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_STO_Case_Record_Page.flexipage-meta.xml

Added LWC to record pages

---

force-app/main/default/flows/HOT_Case_STO_Complete_v_2.flow-meta.xml

Stort sett direkte kopi. Erstattet bruk av Custom Labels med ren tekst kopiert fra norsk oversettelse i sit2

TOLK-2711 legge til kopi av Case STO Completed flow

---

force-app/main/default/flows/HOT_Case_Journal_V2.flow-meta.xml

assign variables manualy
fix referece to Get Thread Record

fix journal flow

---

scripts/bat/newScratchOrg.bat
scripts/bat/newScratchOrgMac

Update scratchOrg scripts

---

force-app/main/default/flows/HOT_Case_Put_Back.flow-meta.xml

Når Thread__c legges til en annen kø, STO_Category__c felter på Case og Thread__c må stemme

fix thread category on put back

---

force-app/main/default/flexipages/HOT_Phone_Case_Record_Page.flexipage-meta.xml

Phone case record page

---

force-app/main/default/customMetadata/HOT_HjelpemiddelsentralMapping.Vestfold_og_Telemark_Hjelpemiddelsentral.md-meta.xml
force-app/main/default/lwc/hot_hjelpemiddelsentral/hot_hjelpemiddelsentral.js

Update HOT_HjelpemiddelsentralMapping og henter region fra kommunenr

---

force-app/main/default/flexipages/HOT_Chat_Case_Record_Page.flexipage-meta.xml

Chat Record Page på Case Objekt
Uten External Syncher komponent

Chat Record Page på case objekt

---

force-app/main/default/flows/HOT_Knowledge_Send_Notification.flow-meta.xml

Knowledge Notification flow change

Knowledge Notification flow change

---

force-app/main/default/flows/HOT_Knowledge_Feedback_notification.flow-meta.xml

Change flow for notification on feedback of article

Change flow for notification on feedback of article

---

force-app/main/default/flexipages/HOT_Chat_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_Phone_Case_Record_Page.flexipage-meta.xml

Add DataSyncer component to all relevant record pages

DataSyncer LWC på record pages

---

force-app/main/default/classes/HOT_GroupSkillSyncScheduler.cls
force-app/main/default/classes/HOT_GroupSkillSyncScheduler.cls-meta.xml
force-app/main/default/classes/HOT_GroupSkillSyncSchedulerTest.cls
force-app/main/default/classes/HOT_GroupSkillSyncSchedulerTest.cls-meta.xml

Scheduler kaller klassen fra sto-repo:
https://github.com/navikt/crm-sto/blob/main/force-app/main/default/classes/STO_GroupMemberSkillService.cls
Som skal opprette/oppdatere ServiceResource for HOT Servicetjenesten med EgeneAnsatte(Skjermede) og Fortrolig Adresse skills

add SkillSyncScheduler

---

force-app/main/default/flows/HOT_Conversation_Note_Journal_Case.flow-meta.xml

Fix recordId variable available for input

Fix recordId variable available for input

---

force-app/main/default/flexipages/HOT_ServicetjenestenAccountRecordPage.flexipage-meta.xml

Added Ny Henvendelse on Account Record page

Added Ny Henvendelse on Account Record page

---

force-app/main/default/permissionsets/HOT_Servicetjenesten.permissionset-meta.xml

La til edit permission på acountName på case

Fix bytt bruker flow og timeline

---

force-app/main/default/queueRoutingConfigs/HOT_Chat_Hjelpemidler_RConfig.queueRoutingConfig-meta.xml
force-app/main/default/queues/HOT_Chat_Hjelpemidler.queue-meta.xml

Chat Queue and Routing Config

---

force-app/main/default/classes/HOT_AccessErrorController.cls
force-app/main/default/classes/HOT_AccessErrorController.cls-meta.xml
force-app/main/default/lwc/hot_accessErrorMessage/hot_accessErrorMessage.html
force-app/main/default/lwc/hot_accessErrorMessage/hot_accessErrorMessage.js
force-app/main/default/lwc/hot_accessErrorMessage/hot_accessErrorMessage.js-meta.xml
force-app/main/default/permissionsets/HOT_Servicetjenesten.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Servicetjenesten_Admin.permissionset-meta.xml

Kopiert fra  nksAccessErrorMessage

TOLK-2910 : LWC som viser om man ikke har tilgang til bruker

---

dummy-data/knowledge/articles.json
dummy-data/knowledge/plan.json
dummy-data/navunits/navtasks.json
dummy-data/navunits/navunits.json
dummy-data/navunits/plan.json
dummy-data/quicktexts/plan.json
dummy-data/quicktexts/quicktexts.json
force-app/main/default/flows/HOT_Case_Log_Call.flow-meta.xml
force-app/main/default/lwc/hot_RecordRefresher/hot_RecordRefresher.js
force-app/main/default/lwc/hot_buttonContainerBottom/hot_buttonContainerBottom.js
force-app/main/default/lwc/hot_conversationNoteButtonContainer/hot_conversationNoteButtonContainer.js
force-app/main/default/lwc/hot_conversationNoteDetails/hot_conversationNoteDetails.js
force-app/main/default/lwc/hot_header/hot_header.js
force-app/main/default/lwc/hot_quickText/hot_quickText.css
force-app/main/default/lwc/hot_quickText/hot_quickText.html
force-app/main/default/lwc/hot_quickText/hot_quickText.js
force-app/main/default/lwc/hot_quickText/hot_quickText.js-meta.xml
force-app/main/default/lwc/hot_redirect/hot_redirect.js
force-app/main/default/lwc/hot_singleRecordInputField/hot_singleRecordInputField.js

Added Conversation Note Signature.

TOLK-2894: Samtalereferat signatur

---

force-app/main/default/flexipages/HOT_Chat_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_Phone_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_STO_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_ServicetjenestenAccountRecordPage.flexipage-meta.xml

Legger til postnummer på lightning pages

---

force-app/main/default/pages/HOT_Chat_PDF.page
force-app/main/default/pages/HOT_Chat_PDF.page-meta.xml

HOT sin egen versjon av Chat PDF Visualforce page

TOLK-2958: HOT Chat Visualforce page

---

force-app/main/default/flexipages/HOT_Chat_Transcript_Record_Page.flexipage-meta.xml

LWC on chat Transcript record page

LWC on chat Transcript record page

---

force-app/main/default/flows/HOT_Chat_Case_Anonymization.flow-meta.xml

HOT_Chat_Case_Anonymization

---

force-app/main/default/flows/HOT_Chat_Journal_Thread.flow-meta.xml
force-app/main/default/flows/HOT_Chat_Send_NAV_Task.flow-meta.xml

Chat Journal og Send Nav Task hadde begge mangler i flowen som er korrigert i denne versjonen

TOLK-3004: Journal and NAV Task flow corrections

---

force-app/main/default/flexipages/HOT_Chat_Transcript_Record_Page.flexipage-meta.xml
force-app/main/default/objects/LiveChatTranscript/fields/HOT_Confidential__c.field-meta.xml
force-app/main/default/permissionsets/HOT_Chat_Permissions.permissionset-meta.xml
force-app/main/default/permissionsets/HOT_Servicetjenesten.permissionset-meta.xml
force-app/scratch-org/homePage/permissionsets/HOT_Servicetjenesten_Admin.permissionset-meta.xml

Added new formula field on Chat Transcript Object
Read only to this new field in permission sets
Record Page filter changed

TOLK-3014 New Formula Field on Chat Transcript object 

---

force-app/main/default/permissionsets/HOT_Servicetjenesten.permissionset-meta.xml

Reverts navikt/crm-hot-servicetjenesten#295

Revert "TOLK-3013: Update HOT_Servicetjenesten permission set"

---

force-app/scratch-org/applications/Servicetjenesten.app-meta.xml

1. Removed assignment from HOT Chat Record Page on Thread Object (We will not use this page)
2. Added assignment (Chat) on HOT Chat STO Record Page (which we will use for both STO and Chat)
3. Removed the Header Title text from component (It will now show Samtale for both STO and Chat)

TOLK-3019: Update Servicetjenesten.app-meta.xml

---

force-app/main/screen-pop/flows/HOT_Inbound_Call.flow-meta.xml

Fjerne unødvendige paths
Trenger ikke organisation eller sjekk på andre ting. trenger bare 2 paths:
1. med personnummer
2. uten personnummer

TOLK-2948 - Oppdatere flow

---

force-app/main/default/lwc/hot_personHighlightPanel/hot_personHighlightPanel.css

TOLK-3033 - Legge til color for tekst i .redBage css for skjermet

TOLK-3033 - Legge til color for tekst i .redBage css for skjermet

---

force-app/main/default/classes/HOT_OEBSIntegrationController.cls
force-app/main/default/classes/HOT_OEBSIntegrationControllerTest.cls
force-app/main/default/permissionsets/HOT_Servicetjenesten.permissionset-meta.xml
force-app/main/integrations/oebs/customMetadata/API_Service_Configuration.GET_OEBS_Brukernr.md-meta.xml

bug fix av bruknr metadata, mock og deserialize

TOLK-3041 - Bug fix

---

force-app/main/default/classes/HOT_PersonBadgesController.cls
force-app/main/default/classes/HOT_PersonBadgesControllerTest.cls
force-app/main/default/customPermissions/HOT_Beta.customPermission-meta.xml
force-app/main/default/flexipages/HOT_Chat_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_Phone_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_STO_Case_Record_Page.flexipage-meta.xml
force-app/main/default/flexipages/HOT_ServicetjenestenAccountRecordPage.flexipage-meta.xml
force-app/main/default/lwc/hot_oebsOrdre/hot_oebsOrdre.html
force-app/main/default/lwc/hot_oebsOrdre/hot_oebsOrdre.js
force-app/main/default/lwc/hot_oebsOrdre/hot_oebsOrdre.js-meta.xml
force-app/main/default/lwc/hot_oebsServiceforesporsel/hot_oebsServiceforesporsel.html
force-app/main/default/lwc/hot_oebsServiceforesporsel/hot_oebsServiceforesporsel.js
force-app/main/default/lwc/hot_oebsServiceforesporsel/hot_oebsServiceforesporsel.js-meta.xml
force-app/main/default/lwc/hot_oebsServiceordre/hot_oebsServiceordre.html
force-app/main/default/lwc/hot_oebsServiceordre/hot_oebsServiceordre.js
force-app/main/default/lwc/hot_oebsServiceordre/hot_oebsServiceordre.js-meta.xml
force-app/main/default/lwc/hot_personHighlightPanel/hot_personHighlightPanel.css
force-app/main/default/lwc/hot_personHighlightPanel/hot_personHighlightPanel.html
force-app/main/default/lwc/hot_personHighlightPanel/hot_personHighlightPanel.js
force-app/main/default/permissionsets/HOT_Servicetjenesten_Beta.permissionset-meta.xml

Dette gjelder:
Ordre
ServiceOrdre
Serviceforespørsel
Brukernummer
Brukerpass
fikset også at hotsak tabellen ikke viste seg på chat case record page.

TOLK-3039 : Legge til OEBS front-end tabeller
